### ISSUE TITLE
Can I run the spiker.py to call peaks using control sample without spike-in read?

### ISSUE THREAD

**Issue by petitmingchang** [liguowang/spiker#3]
I have two files, an Input.bam for control and an H3K27ac.bam for calling peaks.
My case is that only the H3K27ac.bam contains spike-in reads but Input.bam does not.
I already used split_bam.py to separate reads for H3K27ac.bam.
Can I still use spiker.py to call peaks?
If yes, what scaling factor should I set for the control file?
Thank you so much for the help!

**Comment by liguowang** [comment]
In this scenario, I do NOT recommend you use spiker.py to call peaks. You probably need to redo the sequencing of the Input sample with spike-in control.

1. If you have spike-in for both ChIP and input, use this tool to do the peak calling. Spiker.py will scale the sequencing depth according to **external control**.
2. If you don't have spike-in controls for both ChIP and Input, then use MACS2 to do the peak calling. In this case, MACS2 will scale the sequencing depths of ChIP and Input to the **same level**, please note, this step assumes the starting amounts of chromatin are the same (which in general cannot hold).

**Comment by petitmingchang** [comment]
@liguowang I see, thank you so much for your clear explanation.
I have three pairs of ChIP data from H3K4me1, H3K4me3, and H3K27ac between two conditions and would like to compare those peaks between conditions. Since I didn't have the spike-in control, I had used MACS2 to call peaks for each of ChIP data. However, I wonder do we still have the chance to do the normalization according to our spike-in data?

**Comment by liguowang** [comment]
yes, if you think there is global increase/decrease histone methylation levels, you have to have external controls. You can at least manually scale the data at least for differential analyses.

**Comment by petitmingchang** [comment]
@liguowang Got it, thank you very much for your prompt reply!
